on:
  push:
    branches: [main, master]

name: shinylive

jobs:
  shinylive:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with: 
          python-version: '3.8'
      - run: |
          python -m pip install -r requirements.txt
      - name: build static
        run: |
          pip install shinylive
          mkdir ~/.cache/shiny # temp fix for missing dir
          shinylive export app site
      - name: Deploy to GitHub pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: site